-- CreateEnum
CREATE TYPE "GreWordStatus" AS ENUM ('STARTED_LEARNING', 'STILL_LEARNING', 'ALMOST_LEARNT', 'FINISHED_LEARNING', 'MEMORY_MODE', 'MASTERED');

-- AlterTable
ALTER TABLE "GreWords" ADD COLUMN     "status" "GreWordStatus" NOT NULL DEFAULT 'STARTED_LEARNING';
